- name: stop apt-daily
  shell: systemctl stop apt-daily.service apt-daily.timer
  become: yes

- name: disable apt-daily
  shell: systemctl disable apt-daily.service apt-daily.timer
  become: yes

- name: set timezone
  timezone:
    name: Asia/Tokyo
  become: yes

- name: apt update
  apt:
    update_cache: yes
  become: yes

- name: apt upgrade (may wait long time)
  apt:
    upgrade: yes
  become: yes

- name: apt autoremove
  apt:
    autoremove: yes
  become: yes

- name: apt install packages
  apt:
    name:
      - pkg-config
      - vim
      - openssh-server
      - git
      - curl
      - python
  become: yes

- name: get pip installer
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /tmp/

- name: install pip
  command: "python2 /tmp/get-pip.py"
  become: yes

- name: install docker-py
  pip:
    name: docker-py
  become: yes

- name: install docker
  snap:
    name: docker
    classic: yes
    state: present
  become: yes

- name: docker service start
  command: "snap start docker.dockerd"
  become: yes

- name: reboot server (reason... updated security)
  reboot:
  become: yes
